services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./api:/usr/src/api"
      - "/usr/src/api/vendor"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
